CONTROLLER_HEART_BEAT_EXPIRATION = 30
WORKER_HEART_BEAT_INTERVAL = 15

LOGDIR = "."

# Model Constants
IGNORE_INDEX = -100
IMAGE_TOKEN_INDEX = -200
DEFAULT_IMAGE_TOKEN = "<image>"
DEFAULT_IMAGE_PATCH_TOKEN = "<im_patch>"
DEFAULT_IM_START_TOKEN = "<im_start>"
DEFAULT_IM_END_TOKEN = "<im_end>"
IMAGE_PLACEHOLDER = "<image-placeholder>"

# Fusion Constants
DEFAULT_FUSION_VISION_DIM = 2048
DEFAULT_FUSION_HIDDEN_DIM = 128
DEFAULT_FUSION_ALPHA = 256
DEFAULT_FUSION_DROPOUT = 0.1
DEFAULT_FUSION_TARGETS = 'q,k,v'
DEFAULT_FUSION_LAYER_IDS_TO_INJECT = '0'